### ISSUE TITLE
 Cannot read property 'zoom' of undefined

### ISSUE THREAD

**Issue by chelaruc** [hansmaad/chartist-plugin-zoom#13]
Hi, @hansmaad! Thanks for your great work!

Can you tell me how to use this plugin? I was trying to implement this by myself, but i get this error:

<img width="336" alt="screen shot 2017-05-29 at 13 27 47" src="https://cloud.githubusercontent.com/assets/22840626/26546460/b82defb2-4472-11e7-8ce0-c4f155667b03.png">

My code is like that:

       var data = {
          series: [[
            { x: 1, y: 100 },
            { x: 2, y: 50 },
            { x: 3, y: 25 },
            { x: 4, y: 66 },
            { x: 5, y: 30 },
            { x: 6, y: 22 }
          ]]
        };
        var options = {
          axisX: {
            type: Chartist.AutoScaleAxis
          },
          axisY: {
            type: Chartist.AutoScaleAxis
          },
          plugins: [
            Chartist.plugins.zoom({
              onZoom : function(chart, reset) { storeReset(reset); },
            })
          ]
        };

        var chart = new Chartist.Line('.ct-chart', data, options);

**Comment by hansmaad** [comment]
The UMD was messed up. I fixed this with 0.4.1 right now. Please try again.
I tested with browserify:

    var domready = require("domready");
    var Chartist = require('chartist');
    require('chartist-plugin-zoom');

    function storeReset(reset) {
        console.log(reset);
    }

    domready(function () {
        var data = {
            series: [[
                { x: 1, y: 100 },
                { x: 2, y: 50 },
                { x: 3, y: 25 },
                { x: 4, y: 66 },
                { x: 5, y: 30 },
                { x: 6, y: 22 }
            ]]
        };
        var options = {
            axisX: {
                type: Chartist.AutoScaleAxis
            },
            axisY: {
                type: Chartist.AutoScaleAxis
            },
            plugins: [
                Chartist.plugins.zoom({
                onZoom : function(chart, reset) { storeReset(reset); },
                })
            ]
            };

        new Chartist.Line('.ct-chart', data, options);
    });

**Comment by chelaruc** [comment]
I tried again now, but get the same error :(
I'm using angular cli. Can you help me with that?

**Comment by hansmaad** [comment]
Have you installed `npm i --save chartist-plugin-zoom`?
Have you required `require('chartist-plugin-zoom')` ?

Does `npm list chartist-plugin-zoom` print `-- chartist-plugin-zoom@0.4.1`?

**Comment by chelaruc** [comment]
Now i get this error:
<img width="724" alt="screen shot 2017-05-30 at 15 33 14" src="https://cloud.githubusercontent.com/assets/22840626/26583325/710dc996-454d-11e7-9fbe-91bd76efb540.png">

Can you help me to fix it?

**Comment by hansmaad** [comment]
Try to use `import 'chartist-plugin-zoom'`.

**Comment by chelaruc** [comment]
Thanks, it's working now!

**Comment by ashwinkalyanpur** [comment]
I have still issue in the storereset please find the attach.
<img width="420" alt="screen shot 2019-02-12 at 6 05 15 pm" src="https://user-images.githubusercontent.com/3168749/52635808-e88b9000-2ef0-11e9-88a6-9a985a7707e9.png">

**Comment by ashwinkalyanpur** [comment]
I am trying to implement zoom feature for my pie chart now i am facing this problem.
