### ISSUE TITLE
Interfering with custom event handlers

### ISSUE THREAD

**Issue by benhunt29** [hansmaad/chartist-plugin-zoom#7]
I'm attempting to allow the user to adjust the x and y axis min/max values. The way I'm doing this is by tacking on a click event handler on the min/max values (which converts them to inputs) during the draw sequence. This works fine when I don't have your plugin enabled. 

For example, if I make an event handler that listens for clicks on a label element without your plugin enabled, the `event.target` is the label element. But with your plugin enabled, the `event.target` is the entire plot svg and I can't drill down to the actual element clicked.

 Can you think of a reason why your plugin would interfere with the event handlers?

**Comment by hansmaad** [comment]
I'm not sure, but I think the plugin should listen on events on the chart area only, not the entire svg element. I hope I find some time to fix this soon.

**Comment by hansmaad** [comment]
@benhunt29 Could you please check out the new version 0.3.0. I changed event handlers to not handle clicks outside of the chartRect.

**Comment by benhunt29** [comment]
@hansmaad Great, I'll check it out. I looked more into it and ended up just forking your code and adding a transparent "chartArea" rect that covered the plot area and handled all of your listeners. This works but requires me to do some annoying things if I want to allow for other events inside the chart area. From what I see, your solution looks like the better one.

**Comment by benhunt29** [comment]
@hansmaad Seems to work! Thanks for doing that.
